const searchInput = document.getElementById('searchInput');
const wordsContainer = document.querySelector('.words');

const dictionary = [
        { "english": "a", "russian": "неопределённый артикль; один" },
        { "english": "abandon", "russian": "оставлять, покидать" },
        { "english": "ability", "russian": "способность, умение" },
        { "english": "able", "russian": "способный, умеющий" },
        { "english": "aboard", "russian": "на борту" },
        { "english": "about", "russian": "о, об; около" },
        { "english": "above", "russian": "над, выше" },
        { "english": "abroad", "russian": "за границей" },
        { "english": "absence", "russian": "отсутствие" },
        { "english": "absolute", "russian": "абсолютный" },
        { "english": "absolutely", "russian": "абсолютно, совершенно" },
        { "english": "absorb", "russian": "впитывать, поглощать" },
        { "english": "abstract", "russian": "абстрактный; абстракция" },
        { "english": "abuse", "russian": "злоупотребление, злоупотреблять" },
        { "english": "academic", "russian": "академический" },
        { "english": "accept", "russian": "принимать, соглашаться" },
        { "english": "access", "russian": "доступ; получать доступ" },
        { "english": "accident", "russian": "несчастный случай, авария" },
        { "english": "accommodation", "russian": "размещение, жилье" },
        { "english": "accompany", "russian": "сопровождать" },
        { "english": "according", "russian": "согласно" },
        { "english": "account", "russian": "счет; учитывать" },
        { "english": "accurate", "russian": "точный, правильный" },
        { "english": "accuse", "russian": "обвинять" },
        { "english": "achieve", "russian": "достигать, добиваться" },
    
        { "english": "b", "russian": "являться, быть" },
        { "english": "baby", "russian": "младенец" },
        { "english": "back", "russian": "спина; назад" },
        { "english": "background", "russian": "фон, происхождение" },
        { "english": "bad", "russian": "плохой" },
        { "english": "badly", "russian": "плохо" },
        { "english": "bag", "russian": "сумка, мешок" },
        { "english": "balance", "russian": "баланс, равновесие" },
        { "english": "ball", "russian": "мяч, шар" },
        { "english": "ban", "russian": "запрещать, запрет" },
        { "english": "band", "russian": "группа, банда" },
        { "english": "bank", "russian": "банк; берег" },
        { "english": "bar", "russian": "бар; полоса" },
        { "english": "basically", "russian": "в основном, по сути" },
        { "english": "basis", "russian": "основа, база" },
        { "english": "basket", "russian": "корзина" },
        { "english": "bath", "russian": "ванна" },
        { "english": "bathroom", "russian": "ванная комната" },
        { "english": "battle", "russian": "битва, сражение" },
        { "english": "be", "russian": "быть, являться" },
        { "english": "beach", "russian": "пляж" },
        { "english": "bear", "russian": "медведь; нести, выносить" },
        { "english": "beat", "russian": "бить, побить" },
        { "english": "beautiful", "russian": "красивый" },
        { "english": "cabin", "russian": "кабина, хижина" },
        { "english": "cabinet", "russian": "шкаф, кабинет" },
        { "english": "cable", "russian": "кабель, провод" },
        { "english": "calculate", "russian": "вычислять, рассчитывать" },
        { "english": "call", "russian": "звать, звонить; звонок" },
        { "english": "calm", "russian": "спокойный, успокаивать" },
        { "english": "camera", "russian": "камера, фотоаппарат" },
        { "english": "camp", "russian": "лагерь, разбивать лагерь" },
        { "english": "campaign", "russian": "кампания, кампания" },
        { "english": "can", "russian": "мочь, уметь; банка" },
        { "english": "cancel", "russian": "отменять" },
        { "english": "cancer", "russian": "рак (болезнь)" },
        { "english": "candidate", "russian": "кандидат" },
        { "english": "candle", "russian": "свеча" },
        { "english": "cap", "russian": "кепка, шапка" },
        { "english": "capable", "russian": "способный" },
        { "english": "capacity", "russian": "вместимость, способность" },
        { "english": "capital", "russian": "столица, капитал" },
        { "english": "captain", "russian": "капитан" },
        { "english": "capture", "russian": "захватывать, плен" },
        { "english": "car", "russian": "машина, автомобиль" },
        { "english": "card", "russian": "открытка, карта" },
        { "english": "care", "russian": "забота, заботиться" },
        { "english": "career", "russian": "карьера" },
        { "english": "dad", "russian": "папа" },
        { "english": "daily", "russian": "ежедневный; ежедневно" },
        { "english": "damage", "russian": "повреждение, повреждать" },
        { "english": "dance", "russian": "танцевать; танец" },
        { "english": "danger", "russian": "опасность" },
        { "english": "dangerous", "russian": "опасный" },
        { "english": "dare", "russian": "осмеливаться, вызов" },
        { "english": "dark", "russian": "тёмный; темнота" },
        { "english": "darkness", "russian": "темнота" },
        { "english": "data", "russian": "данные" },
        { "english": "date", "russian": "дата; свидание" },
        { "english": "daughter", "russian": "дочь" },
        { "english": "day", "russian": "день" },
        { "english": "dead", "russian": "мёртвый" },
        { "english": "deadline", "russian": "крайний срок" },
        { "english": "deal", "russian": "сделка; иметь дело" },
        { "english": "dear", "russian": "дорогой; дорого" },
        { "english": "death", "russian": "смерть" },
        { "english": "debate", "russian": "дебаты, обсуждать" },
        { "english": "debt", "russian": "долг" },
        { "english": "decade", "russian": "десятилетие" },
        { "english": "decide", "russian": "решать" },
        { "english": "decision", "russian": "решение" },
        { "english": "declare", "russian": "объявлять, заявлять" },
        { "english": "each", "russian": "каждый" },
        { "english": "ear", "russian": "ухо" },
        { "english": "earlier", "russian": "раньше" },
        { "english": "early", "russian": "ранний, рано" },
        { "english": "earn", "russian": "зарабатывать" },
        { "english": "earth", "russian": "земля" },
        { "english": "easily", "russian": "легко" },
        { "english": "east", "russian": "восток" },
        { "english": "easy", "russian": "легкий" },
        { "english": "eat", "russian": "есть" },
        { "english": "economic", "russian": "экономический" },
        { "english": "economy", "russian": "экономика" },
        { "english": "edge", "russian": "край" },
        { "english": "edition", "russian": "издание" },
        { "english": "editor", "russian": "редактор" },
        { "english": "effect", "russian": "эффект, воздействие" },
        { "english": "effective", "russian": "эффективный" },
        { "english": "effort", "russian": "усилие" },
        { "english": "eight", "russian": "восемь" },
        { "english": "either", "russian": "либо, или" },
        { "english": "election", "russian": "выборы" },
        { "english": "electric", "russian": "электрический" },
        { "english": "element", "russian": "элемент" },
        { "english": "else", "russian": "ещё" },
        { "english": "face", "russian": "лицо, сталкиваться" },
        { "english": "fact", "russian": "факт" },
        { "english": "factor", "russian": "фактор, множитель" },
        { "english": "factory", "russian": "фабрика" },
        { "english": "fail", "russian": "провалиться, потерпеть неудачу" },
        { "english": "failure", "russian": "неудача" },
        { "english": "faint", "russian": "слабый, слабый" },
        { "english": "fair", "russian": "справедливый, честный" },
        { "english": "faith", "russian": "вера" },
        { "english": "fall", "russian": "падать, осень" },
        { "english": "false", "russian": "ложный, неверный" },
        { "english": "familiar", "russian": "знакомый, familiar" },
        { "english": "family", "russian": "семья" },
        { "english": "famous", "russian": "знаменитый" },
        { "english": "fan", "russian": "поклонник, фанат" },
        { "english": "fancy", "russian": "роскошь; воображать" },
        { "english": "far", "russian": "далеко" },
        { "english": "farm", "russian": "ферма" },
        { "english": "farmer", "russian": "фермер" },
        { "english": "fashion", "russian": "мода" },
        { "english": "fast", "russian": "быстрый, быстро" },
        { "english": "fat", "russian": "толстый" },
        { "english": "father", "russian": "отец" },
        { "english": "fault", "russian": "вина, недостаток" },
        { "english": "gain", "russian": "получать, приобретать; прибыль" },
        { "english": "gallery", "russian": "галерея" },
        { "english": "game", "russian": "игра" },
        { "english": "gap", "russian": "пробел, разрыв" },
        { "english": "garage", "russian": "гараж" },
        { "english": "garden", "russian": "сад" },
        { "english": "garlic", "russian": "чеснок" },
        { "english": "gas", "russian": "газ" },
        { "english": "gate", "russian": "ворота" },
        { "english": "gather", "russian": "собирать" },
        { "english": "general", "russian": "общий, генерал" },
        { "english": "generally", "russian": "обычно, в основном" },
        { "english": "generate", "russian": "генерировать, создавать" },
        { "english": "generation", "russian": "поколение" },
        { "english": "gentle", "russian": "мягкий, нежный" },
        { "english": "gentleman", "russian": "джентльмен" },
        { "english": "get", "russian": "получать, становиться" },
        { "english": "ghost", "russian": "призрак" },
        { "english": "giant", "russian": "гигант" },
        { "english": "gift", "russian": "подарок" },
        { "english": "girl", "russian": "девочка" },
        { "english": "give", "russian": "давать" },
        { "english": "glad", "russian": "радый" },
        { "english": "hair", "russian": "волосы" },
        { "english": "half", "russian": "половина" },
        { "english": "hall", "russian": "зал, холл" },
        { "english": "hand", "russian": "рука" },
        { "english": "handle", "russian": "ручка; обращаться" },
        { "english": "hang", "russian": "висеть, вешать" },
        { "english": "happen", "russian": "случаться" },
        { "english": "happy", "russian": "счастливый" },
        { "english": "hard", "russian": "трудный; усердно" },
        { "english": "harm", "russian": "вред, вредить" },
        { "english": "harvest", "russian": "урожай; собирать урожай" },
        { "english": "hat", "russian": "шляпа" },
        { "english": "hate", "russian": "ненавидеть; ненависть" },
        { "english": "have", "russian": "иметь" },
        { "english": "he", "russian": "он (местоимение)" },
        { "english": "head", "russian": "голова" },
        { "english": "heading", "russian": "заголовок" },
        { "english": "health", "russian": "здоровье" },
        { "english": "hear", "russian": "слышать" },
        { "english": "heart", "russian": "сердце" },
        { "english": "heat", "russian": "жара, нагревать" },
        { "english": "heavy", "russian": "тяжёлый" },
        { "english": "hell", "russian": "ад" },
        { "english": "hello", "russian": "привет" },
        { "english": "i", "russian": "Я" },
        { "english": "ice", "russian": "лёд" },
        { "english": "idea", "russian": "идея" },
        { "english": "ideal", "russian": "идеальный" },
        { "english": "identify", "russian": "определять, опознавать" },
        { "english": "identity", "russian": "личность, идентичность" },
        { "english": "if", "russian": "если" },
        { "english": "ignore", "russian": "игнорировать" },
        { "english": "ill", "russian": "больной" },
        { "english": "illegal", "russian": "незаконный" },
        { "english": "imagine", "russian": "представлять, воображать" },
        { "english": "image", "russian": "изображение, образ" },
        { "english": "immediate", "russian": "немедленный, непосредственный" },
        { "english": "immense", "russian": "огромный, необъятный" },
        { "english": "impact", "russian": "влияние, воздействие" },
        { "english": "imply", "russian": "подразумевать, подразумевать" },
        { "english": "important", "russian": "важный" },
        { "english": "impossible", "russian": "невозможный" },
        { "english": "impress", "russian": "впечатлять" },
        { "english": "improve", "russian": "улучшать" },
        { "english": "in", "russian": "в (предлог)" },
        { "english": "inch", "russian": "дюйм" },
        { "english": "include", "russian": "включать, содержать" },
        { "english": "income", "russian": "доход" },
        { "english": "indeed", "russian": "действительно, в самом деле" },
        { "english": "jack", "russian": "Джек (имя), домкрат" },
        { "english": "jacket", "russian": "куртка, пиджак" },
        { "english": "jail", "russian": "тюрьма" },
        { "english": "jam", "russian": "варенье; застревать" },
        { "english": "january", "russian": "январь" },
        { "english": "jealous", "russian": "ревнивый" },
        { "english": "jeans", "russian": "джинсы" },
        { "english": "jelly", "russian": "желе, студень" },
        { "english": "jewel", "russian": "драгоценность" },
        { "english": "job", "russian": "работа" },
        { "english": "join", "russian": "присоединяться, соединять" },
        { "english": "joint", "russian": "совместный, сустав" },
        { "english": "joke", "russian": "шутка" },
        { "english": "journal", "russian": "журнал, дневник" },
        { "english": "journey", "russian": "путешествие" },
        { "english": "judge", "russian": "судья, судить" },
        { "english": "judgment", "russian": "суждение, приговор" },
        { "english": "juice", "russian": "сок" },
        { "english": "july", "russian": "июль" },
        { "english": "jump", "russian": "прыгать, прыжок" },
        { "english": "june", "russian": "июнь" },
        { "english": "junior", "russian": "младший; юный" },
        { "english": "jury", "russian": "присяжные" },
        { "english": "just", "russian": "просто, только; как раз" },
        { "english": "keen", "russian": "острый; увлеченный" },
        { "english": "keep", "russian": "держать, хранить, соблюдать" },
        { "english": "key", "russian": "ключ" },
        { "english": "kick", "russian": "пинать, удар ногой" },
        { "english": "kid", "russian": "ребенок, пацан" },
        { "english": "kidney", "russian": "почка" },
        { "english": "kill", "russian": "убивать" },
        { "english": "kind", "russian": "добрый, вид, тип" },
        { "english": "king", "russian": "король" },
        { "english": "kiss", "russian": "поцелуй, целовать" },
        { "english": "kitchen", "russian": "кухня" },
        { "english": "knee", "russian": "колено" },
        { "english": "knife", "russian": "нож" },
        { "english": "knock", "russian": "стучать" },
        { "english": "know", "russian": "знать" },
        { "english": "knowledge", "russian": "знание" },
        { "english": "lab", "russian": "лаборатория" },
        { "english": "lack", "russian": "нехватка, недостаток" },
        { "english": "lady", "russian": "леди, дама" },
        { "english": "lake", "russian": "озеро" },
        { "english": "land", "russian": "земля, приземляться" },
        { "english": "landscape", "russian": "пейзаж" },
        { "english": "language", "russian": "язык" },
        { "english": "large", "russian": "большой" },
        { "english": "last", "russian": "последний, длиться" },
        { "english": "late", "russian": "поздний, поздно" },
        { "english": "laugh", "russian": "смеяться, смех" },
        { "english": "law", "russian": "закон" },
        { "english": "lawyer", "russian": "адвокат" },
        { "english": "lay", "russian": "класть, положить" },
        { "english": "lazy", "russian": "ленивый" },
        { "english": "lead", "russian": "вести, приводить; свинец" },
        { "english": "leader", "russian": "лидер" },
        { "english": "leadership", "russian": "лидерство" },
        { "english": "leading", "russian": "ведущий, главный" },
        { "english": "leaf", "russian": "лист (дерева)" },
        { "english": "learn", "russian": "учить, изучать" },
        { "english": "least", "russian": "наименьший" },
        { "english": "leather", "russian": "кожа" },
        { "english": "leave", "russian": "оставлять, уходить" },
        { "english": "lecture", "russian": "лекция, читать лекцию" },
        { "english": "left", "russian": "левый" },
        { "english": "leg", "russian": "нога (от бедра)" },
        { "english": "legal", "russian": "юридический, законный" },
        { "english": "lend", "russian": "одалживать" },
        { "english": "length", "russian": "длина" },
        { "english": "less", "russian": "меньше" },
        { "english": "lesson", "russian": "урок" },
        { "english": "machine", "russian": "машина" },
        { "english": "magazine", "russian": "журнал" },
        { "english": "magic", "russian": "магия, волшебный" },
        { "english": "mail", "russian": "почта; отправлять по почте" },
        { "english": "main", "russian": "главный, основной" },
        { "english": "mainly", "russian": "главным образом" },
        { "english": "maintain", "russian": "поддерживать, сохранять" },
        { "english": "major", "russian": "главный, майор" },
        { "english": "majority", "russian": "большинство" },
        { "english": "make", "russian": "делать" },
        { "english": "male", "russian": "мужской, мужчина" },
        { "english": "man", "russian": "человек, мужчина" },
        { "english": "manage", "russian": "управлять, справляться" },
        { "english": "management", "russian": "управление, руководство" },
        { "english": "manager", "russian": "менеджер, управляющий" },
        { "english": "manner", "russian": "манера, способ" },
        { "english": "manufacture", "russian": "производство, производить" },
        { "english": "many", "russian": "много" },
        { "english": "map", "russian": "карта" },
        { "english": "march", "russian": "март; маршировать" },
        { "english": "mark", "russian": "отметка, отмечать" },
        { "english": "market", "russian": "рынок" },
        { "english": "marriage", "russian": "брак" },
        { "english": "marry", "russian": "жениться, выходить замуж" },
        { "english": "nail", "russian": "гвоздь; ноготь" },
        { "english": "name", "russian": "имя, называть" },
        { "english": "narrative", "russian": "повествование, рассказ" },
        { "english": "narrow", "russian": "узкий" },
        { "english": "nation", "russian": "нация" },
        { "english": "national", "russian": "национальный" },
        { "english": "native", "russian": "родной, местный" },
        { "english": "natural", "russian": "естественный" },
        { "english": "nature", "russian": "природа" },
        { "english": "navy", "russian": "военно-морской флот" },
        { "english": "near", "russian": "близкий, около" },
        { "english": "nearly", "russian": "почти" },
        { "english": "necessary", "russian": "необходимый" },
        { "english": "neck", "russian": "шея" },
        { "english": "need", "russian": "нуждаться; необходимость" },
        { "english": "needle", "russian": "игла" },
        { "english": "negative", "russian": "отрицательный" },
        { "english": "negotiate", "russian": "вести переговоры" },
        { "english": "neighbor", "russian": "сосед" },
        { "english": "neither", "russian": "ни тот, ни другой" },
        { "english": "nerve", "russian": "нерв" },
        { "english": "nervous", "russian": "нервный, взволнованный" },
        { "english": "net", "russian": "сеть" },
        { "english": "never", "russian": "никогда" },
         { "english": "object", "russian": "объект; возражать" },
         { "english": "objective", "russian": "цель, объективный" },
         { "english": "obligation", "russian": "обязательство" },
         { "english": "observe", "russian": "наблюдать, замечать" },
         { "english": "obtain", "russian": "получать, приобретать" },
         { "english": "obviously", "russian": "очевидно" },
         { "english": "occasion", "russian": "случай, повод" },
         { "english": "ocean", "russian": "океан" },
         { "english": "October", "russian": "октябрь" },
         { "english": "odd", "russian": "странный, нечетный" },
         { "english": "of", "russian": "из, от (родительный падеж)" },
         { "english": "off", "russian": "с, от (предлог)" },
         { "english": "offer", "russian": "предложение, предлагать" },
         { "english": "office", "russian": "офис, кабинет" },
         { "english": "officer", "russian": "офицер" },
         { "english": "official", "russian": "официальный; чиновник" },
         { "english": "often", "russian": "часто" },
         { "english": "oil", "russian": "масло; нефть" },
         { "english": "old", "russian": "старый" },
         { "english": "on", "russian": "на (предлог)" },
         { "english": "once", "russian": "однажды, раз" },
         { "english": "one", "russian": "один" },
         { "english": "ongoing", "russian": "продолжающийся, текущий" },
         { "english": "onion", "russian": "лук" },
        { "english": "pack", "russian": "упаковывать; упаковка" },
        { "english": "package", "russian": "упаковка, пакет" },
        { "english": "page", "russian": "страница" },
        { "english": "pain", "russian": "боль" },
        { "english": "paint", "russian": "краска, рисовать" },
        { "english": "painter", "russian": "художник" },
        { "english": "painting", "russian": "картина, живопись" },
        { "english": "pair", "russian": "пара" },
        { "english": "palace", "russian": "дворец" },
        { "english": "pale", "russian": "бледный" },
        { "english": "pan", "russian": "сковорода" },
        { "english": "panel", "russian": "панель, секция" },
        { "english": "pants", "russian": "брюки" },
        { "english": "paper", "russian": "бумага" },
        { "english": "parent", "russian": "родитель" },
        { "english": "park", "russian": "парк; парковать" },
        { "english": "parliament", "russian": "парламент" },
        { "english": "part", "russian": "часть" },
        { "english": "participant", "russian": "участник" },
        { "english": "participate", "russian": "участвовать" },
        { "english": "particular", "russian": "особенный, конкретный" },
        { "english": "particularly", "russian": "особенно" },
        { "english": "partly", "russian": "частично" },
        { "english": "partner", "russian": "партнер" },
        { "english": "qualify", "russian": "квалифицировать, соответствовать" },
        { "english": "quality", "russian": "качество" },
        { "english": "quantity", "russian": "количество" },
        { "english": "quarter", "russian": "четверть, квартал" },
        { "english": "queen", "russian": "королева" },
        { "english": "question", "russian": "вопрос; спрашивать" },
        { "english": "quick", "russian": "быстрый" },
        { "english": "quickly", "russian": "быстро" },
        { "english": "quiet", "russian": "тихий, спокойный" },
        { "english": "quit", "russian": "бросать, уходить" },
        { "english": "quite", "russian": "вполне, довольно" },
        { "english": "quote", "russian": "цитата, цитировать" },
        { "english": "race", "russian": "гонка, раса" },
        { "english": "racial", "russian": "расовый" },
        { "english": "radio", "russian": "радио" },
        { "english": "rail", "russian": "рельс" },
        { "english": "railroad", "russian": "железная дорога" },
        { "english": "rain", "russian": "дождь, идти дождь" },
        { "english": "raise", "russian": "поднимать, повышать" },
        { "english": "range", "russian": "диапазон, ряд" },
        { "english": "rank", "russian": "ранг, звание" },
        { "english": "rapid", "russian": "быстрый, стремительный" },
        { "english": "rare", "russian": "редкий" },
        { "english": "rarely", "russian": "редко" },
        { "english": "rate", "russian": "ставка, оценивать" },
];
function highlightSearchTerm(text, searchTerm) {
    if (!searchTerm) {
        return text; 
    }
    const regex = new RegExp(searchTerm, 'gi'); 
    return text.replace(regex, match => `<span class="highlight">${match}</span>`);
}
function displayWords(words, searchTerm = '') {
    wordsContainer.innerHTML = '';
    const wordGroups = {};
    words.forEach(word => {
        const firstLetter = word.english.charAt(0).toUpperCase();

        if (!wordGroups[firstLetter]) {
            wordGroups[firstLetter] = [];
        }

        wordGroups[firstLetter].push(word);
    });
    for (const letter in wordGroups) {
        if (wordGroups.hasOwnProperty(letter)) {
            const wordGroup = document.createElement('div');
            wordGroup.classList.add('word');

            const heading = document.createElement('h2');
            heading.textContent = letter;
            wordGroup.appendChild(heading);

            const list = document.createElement('ul');
            wordGroups[letter].forEach(word => {
                const highlightedEnglish = highlightSearchTerm(word.english, searchTerm);
                const highlightedRussian = highlightSearchTerm(word.russian, searchTerm);

                const listItem = document.createElement('li');
                listItem.innerHTML = `<span class="firstword">${highlightedEnglish}</span> <span class="lastword">${highlightedRussian}</span>`;
                list.appendChild(listItem);
            });

            wordGroup.appendChild(list);
            wordsContainer.appendChild(wordGroup);
        }
    }
}
searchInput.addEventListener('input', () => {
    const searchTerm = searchInput.value.toLowerCase();
    const filteredWords = dictionary.filter(word =>
        word.english.toLowerCase().includes(searchTerm) || word.russian.toLowerCase().includes(searchTerm));
    displayWords(filteredWords, searchTerm);
});
displayWords(dictionary);